#!/usr/bin/env sh

set -e

nix-build
result/bin/kubecert \
    ca \
    --common-name ca.name \
    tmp/ca

result/bin/kubecert \
    cert \
    --common-name common.name \
    --kind client \
    --ca-path tmp/ca \
    tmp/client_cert

result/bin/kubecert \
    cert \
    --common-name common.name \
    --kind server \
    --ca-path tmp/ca \
    --additional-address 1.2.3.4 \
    --additional-address 5.6.7.8 \
    tmp/server_cert
